// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlUgCg9QC1zeMUgBtqzXcU7NUZbdg-2y8',
    appId: '1:716375699807:web:2f24c4e60f36694e1a06ea',
    messagingSenderId: '716375699807',
    projectId: 'nambu-admin-20246',
    authDomain: 'nambu-admin-20246.firebaseapp.com',
    storageBucket: 'nambu-admin-20246.firebasestorage.app',
    measurementId: 'G-P46TXC911M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnwrS7i0ZUsdYp0FrgtbjbwxYnu7vYzRw',
    appId: '1:716375699807:android:ceb0090af4918d291a06ea',
    messagingSenderId: '716375699807',
    projectId: 'nambu-admin-20246',
    storageBucket: 'nambu-admin-20246.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKfIH0yUghpI6bscEEMhAJXnlqICEX93s',
    appId: '1:716375699807:ios:f7f56f449ab977a11a06ea',
    messagingSenderId: '716375699807',
    projectId: 'nambu-admin-20246',
    storageBucket: 'nambu-admin-20246.firebasestorage.app',
    iosBundleId: 'com.example.nambuAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKfIH0yUghpI6bscEEMhAJXnlqICEX93s',
    appId: '1:716375699807:ios:f7f56f449ab977a11a06ea',
    messagingSenderId: '716375699807',
    projectId: 'nambu-admin-20246',
    storageBucket: 'nambu-admin-20246.firebasestorage.app',
    iosBundleId: 'com.example.nambuAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlUgCg9QC1zeMUgBtqzXcU7NUZbdg-2y8',
    appId: '1:716375699807:web:26c2fe1d45cae72d1a06ea',
    messagingSenderId: '716375699807',
    projectId: 'nambu-admin-20246',
    authDomain: 'nambu-admin-20246.firebaseapp.com',
    storageBucket: 'nambu-admin-20246.firebasestorage.app',
    measurementId: 'G-TH5Z80GC46',
  );
}
